@startuml
skinparam componentStyle uml2
database LDAP
database Database as db
storage Storage
node "WildFly AS" {
[Archive] as arc
[Keycloak] as kc
}
storage "Elastic Stack" as elk
() HTTP as http1
() HTTP as http2
() HTTP as http3
LDAP <-- kc
kc -- http1
LDAP <-- arc
db <-- arc
Storage <-- arc
kc <- arc
arc -- DICOM
arc -- HL7v2
arc -- http2
elk <-- arc
elk -- http3
@enduml