@startuml
skinparam componentStyle uml2
node "" <<Docker Container>> {
database LDAP as ldap
}
node "" <<Docker Container>> {
node "Wildfly AS" as wf1 {
[Keycloak] as kc
}
}
node "" <<Docker Container>> {
node "Wildfly AS" {
[Archive] as arc
}
}
node "" <<Docker Container>> {
database "Database" as db
}
node "" <<Docker Container>> {
storage Storage
}
node "" <<Docker Container>> {
[Logstash] <- arc
}
node "" <<Docker Container>> {
storage Elasticsearch
}
node "" <<Docker Container>> {
Elasticsearch <- [Kibana]
}
() HTTP as http1
() HTTP as http2
() HTTP as http3
arc --> kc
ldap <-- kc
ldap <- arc
db <- arc
Storage <- arc
Logstash -> Elasticsearch
kc - http1
arc -- DICOM
arc -- HL7v2
arc -- http2
Kibana - http3
@enduml